constants:
  BITBUCKET_API_BASE_URL: "https://api.bitbucket.org"
  BITBUCKET_OAUTH2_URL: "https://bitbucket.org/site/oauth2"
  CLIENT_ID: "YOUR_CLIENT_ID"
  CLIENT_SECRET: "YOUR_SECRET"
  CALLBACK_URL: "https://localhost:3000/callback"
